username: sngndncmn
password: coffee

application_name: HealthCare Insight&copy

issuu_key: "7epzck3p0csmgo3yo7kpfwwebwnuwxs4"
issuu_secret: "m82b78tie0336wqffajbhrwedgatejlw"

job_posting_link: "http://jobs-verisk.icims.com/jobs/search?ss=1&searchKeyword=&searchLocation=&searchCategory=&searchCompany=77&searchPostedDate"