--- 
javascripts: 
- base:
  - jquery
  - jquery.livequery
  - jqueryui
  - jquery.easing
  - jQueryTimer
  - jquery.alerts
  - jquery.validate
  - reflection
  - swfobject
  - accordion
  - flowplayer
  - application
  - scroll
  - video_scripts
stylesheets: 
- base:
  - reset-fonts-grids
  - jquiwidgets
  - "960"
  - "alerts/jquery.alerts"
  - application
