development:
  email_settings:
    delivery_method: sendmail
    address: smtp.gmail.com
    port: 587
    user_name: stophealthcarefraud@gmail.com
    password: rockstar
    authentication: :plain
    
stage:
  email_settings:
    delivery_method: smtp
    address: smtpout.secureserver.net
    port: 25
    domain: stopheatlhcarefraud.com
    authentication: login
    username: 25015209
    password: 239133
    contact_recipient: webmaster@stophealthcarefraud.com
    
production:
  email_settings:
    delivery_method: sendmail
    contact_recipient: info@stophealthcarefraud.com
    
test:
  fms_host: localhost:3000
  disable_google_ads: false
  email:
    delivery_method: test
    contact_recipient: info@stophealthcarefraud.com