--- 
- :version: ">= 4.1.1"
  :source: http://code.whytheluckystiff.net
  :name: RedCloth
- :name: authlogic
- :version: ~> 2.3.11
  :source: http://gemcutter.org
  :name: will_paginate
- :version: = 1.3.16
  :name: thinking-sphinx
- :version: 2.3.5
  :name: rails
