--- 
- :version: ">= 4.2.3"
  :source: http://gemcutter.org
  :name: RedCloth
- :name: authlogic
- :version: ~> 2.3.11
  :source: http://gemcutter.org
  :name: will_paginate
- :version: = 1.3.18
  :name: thinking-sphinx
- :version: 2.3.8
  :name: rails
