--- 
- :source: http://gemcutter.org
  :version: ">= 4.2.3"
  :name: RedCloth
- :name: authlogic
- :source: http://gemcutter.org
  :version: ~> 2.3.11
  :name: will_paginate
- :version: = 1.3.16
  :name: thinking-sphinx
- :version: 2.3.8
  :name: rails
