--- 
- :version: ">= 4.2.3"
  :source: http://gemcutter.org
  :name: RedCloth
- :version: ~> 2.1.6
  :source: http://rubygems.org
- :name: authlogic
- :version: ~> 2.3.15
  :source: http://gemcutter.org
  :name: will_paginate
- :version: = 1.3.20
  :name: thinking-sphinx
- :version: 2.3.8
  :name: rails
