:ruby: ree

# Stage Env
:application: stage_hci
:user: rails
:deploy_to: /var/www/apps/stage_hci
:domain: stage.hcinsight.com
:domain_aliases:
  - stage.hcinsight.com

:repository: git@github.com:electricgraffitti/hci_hci.git
:branch: silverrack_deploy_stage

# Production Env - **************MAKE SURE TO SWAP THE SPHINX FILE TOO!!!!!
# :application: hci
# :user: rails
# :deploy_to: /var/www/apps/hci
# :domain: hcinsight.com
# :domain_aliases:
#   - www.hcinsight.com
# 
# :repository: git@github.com:electricgraffitti/hci_hci.git
# :branch: silverrack_deploy_stage

# Use :app_symlinks to setup directories under public/ that you want to persist
# across deployments. They'll be symlinked to the shared directory.
:app_symlinks:
 - avatars
 - attachments
 - case_studies
 - brochures
 - covers
 - videos
 - video_thumbs
 - landing_page_stylesheets
 - landing_page_images
 - ad_images
 - banners
 - tutorial_videos
 - tutorial_video_thumbs
#
# Use :local_config to copy directories straight from your local project directory
# to the server: these are files that you don't have/want in scm.
:local_config:
 - config/database.yml
 - config/app_config.yml
#
# The entries in shared_children are created in #{application}/shared
:shared_children:
- system
- log
- pids
- config

:rubygems:
  :sources:
    - http://gemcutter.org
    - http://gems.rubyforge.org
    - http://gems.github.com

# After specifying a gem with config.gem, run 'rake moonshine:gems'
# to update config/gems.yml. If the gem depends on native packages, 
# tell Moonshine here:
:apt_gems:
  :paperclip:
    - imagemagick
#:apt_gems:
#  :awesomegem:
#    - awesome
#    - libawesome-dev
#
# See all the options for Passenger, Apache vhosts, and MySQL in the
# respective templates: moonshine/lib/moonshine/manifest/rails/templates
:passenger:
  :max_pool_size: 2
  :use_global_queue: true
:mysql:
  :innodb_buffer_pool_size: 128M
  