development:
 port: 3312
test:
 port: 3312

production:
 config_file: /var/www/apps/stage_hci/shared/config/production.sphinx.conf
 searchd_file_path: /var/www/apps/stage_hci/shared/db/sphinx/production
 searchd_log_file: /var/www/apps/stage_hci/shared/log/searchd.log
 query_log_file: /var/www/apps/stage_hci/shared/log/searchd.query.log
 pid_file: /var/www/apps/shcf/stage_hci/pids/searchd.production.pid
 port: 3312
 address: 67.23.25.218
 