development:
  port: 3302
test:
  port: 3302
production:
  port: 3302




production:
    config_file: /var/www/apps/stage_hci/shared/config/production.sphinx.conf
    searchd_file_path: /var/www/apps/stage_hci/shared/db/sphinx/production
    searchd_log_file: /var/www/apps/stage_hci/shared/log/searchd.log
    query_log_file: /var/www/apps/stage_hci/shared/log/searchd.query.log
    pid_file: /var/www/apps/shcf/stage_hci/pids/searchd.production.pid